/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/Pink_Ghost.glb --types --transform 
Files: src/assets/Pink_Ghost.glb [51.41KB] > C:\Users\diego\Desktop\TFG-RusticPacman\testing_react-three-fiber\pacman-r3f\Pink_Ghost-transformed.glb [9.91KB] (81%)
*/

import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
  const { nodes, materials } = useGLTF('assets/Pink_Ghost-transformed.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.001']} position={[-0.373, 0, 0.811]} scale={0.205} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.003']} position={[-0.399, 0, 0.961]} scale={0.083} />
    </group>
  )
}

useGLTF.preload('assets/Pink_Ghost-transformed.glb')
