/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/Red_Ghost.glb --types --transform 
Files: src/assets/Red_Ghost.glb [51.41KB] > C:\Users\diego\Desktop\TFG-RusticPacman\testing_react-three-fiber\pacman-r3f\Red_Ghost-transformed.glb [9.78KB] (81%)
*/

import { useGLTF } from '@react-three/drei'


export function Model(props: any) {
  const { nodes, materials } = useGLTF('assets/Red_Ghost-transformed.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.004']} position={[0.416, 0.014, 0.961]} scale={0.083} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.002']} position={[0.4, 0, 0.811]} scale={0.205} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('assets/Red_Ghost-transformed.glb')
