enum gameStatusValue {
  NOT_STARTED = "NOT_STARTED",
  GENERATING_MAZE = "GENERATING_MAZE",
  SETTING_PACMAN = "SETTING_PACMAN",
  SETTING_GHOSTS = "SETTING_GHOSTS",
  PLAYING = "PLAYING",
  PAUSED = "PAUSED",
  LOST = "LOST",
  WON = "WON",
  RESTARTING = "RESTARTING"
}

export default gameStatusValue;