enum gameStatusValue {
  INITIAL_LOADING = "INITIAL_LOADING",
  NOT_STARTED = "NOT_STARTED",
  DEBUG_MAZE_ANALYZER = "DEBUG_MAZE_ANALYZER",
  DEBUG_SETTINGS = "DEBUG_SETTINGS",
  READY_TO_LOAD = "READY_TO_LOAD",
  LOADING_CORE = "LOADING_CORE",
  CORE_LOADED = "CORE_LOADED",
  LOADING_GRAPHICS = "LOADING_GRAPHICS",
  GRAPHICS_LOADED = "GRAPHICS_LOADED",
  PLAYING = "PLAYING",
  PAUSED = "PAUSED",
  LOST = "LOST",
  WON = "WON",
  RESTARTING = "RESTARTING",
  TUTORIAL = "TUTORIAL"
}

export default gameStatusValue;